export const DEFAULT_DIR_START_INITIATOR_SHOW = true;
export const DEFAULT_DIR_MIN_DELAY = 8;
export const DEFAULT_DIR_MIN_DIST = 2;
export const DIR_SHOW_START_INITIATOR_TIME = 2500;
export const DIR_HIDE_START_INITIATOR_TIME = 250;

export const DEFAULT_DIR_LONG_PRESS_TIME = 0;
export const DEFAULT_DIR_LONG_PRESS_AFTER_EFFECT_TIME = 0;
export const DEFAULT_DIR_LONG_PRESS_EFFECT_DELAY = 0;
export const DEFAULT_DIR_LONG_PRESS_REVERT_EFFECT_TIME = 0;