export const DEFAULT_LASSO_START_INDICATOR_SHOW = true;
export const DEFAULT_LASSO_START_INDICATOR_COLOR = 'rgba(255, 255, 255, 0.1)';
export const DEFAULT_LASSO_MIN_DELAY = 8;
export const DEFAULT_LASSO_MIN_DIST = 2;
export const LASSO_SHOW_START_INDICATOR_TIME = 2500;
export const LASSO_HIDE_START_INDICATOR_TIME = 250;
